.metadata <- read_excel('data-raw/CVPIA_FloodplainAreas_docs.xlsx', sheet = 'R_Ready',
                        col_types = c(rep('text', 4),
                                      rep('numeric', 19), 'text',
                                      'numeric', 'text'))

# modeling details------------------------------------
print_model_details <- function(ws, species) {
  
  watershed_doc_vars <- filter(.metadata, watershed == ws)
  
  if (species == 'sr' & is.na(watershed_doc_vars$SR_length_modeled_mi)) {
    warning(sprintf('There are no spring run in %s.', ws))
    return(NULL)
  }
  
  watershed_method <- watershed_doc_vars$method
  
  switch(species,
         'fr' = switch(watershed_method,
                       'full_model_t' = "The entire mapped rearing extent of 54.33 miles was modeled by TID and MID using a TUFLOW hydraulic model with 1D channel and 2D overbank components. This approach directly modeled  inundated floodplain area.",
                       'full_model_nmfs' = sprintf('The entire mapped rearing extent of %.2f miles was modeled using %s. The high quality depth and high quality velocity ("Pref11") "BankArea" result was used as floodplain area. High quality velocities were assumed to be less than or equal to 0.15 meters per second, and high quality depths were assumed to be between 0.2 meters and 1.5 meters.', 
                                              watershed_doc_vars$FR_rearing_length_mi, 
                                              watershed_doc_vars$model_name),
                       'full_model' = sprintf("The entire mapped rearing extent of %.2f miles was modeled using %s. Active channel area of %.2f acres estimated through remote sensing analysis was subtracted from total inundated area to get inundated floodplain area.", 
                                              watershed_doc_vars$FR_rearing_length_mi, 
                                              watershed_doc_vars$model_name, 
                                              watershed_doc_vars$FR_channel_area_of_length_modeled_acres),
                       'scaled_dc' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for Deer Creek based onhydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of DeerCreek values based on the ratio of mean flow from December to June between this watershed and Deer Creek. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.', 
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$FR_rearing_length_mi, 
                                             watershed_doc_vars$FR_low_gradient_length_mi, 
                                             watershed_doc_vars$FR_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'part_model' = sprintf('A %.2f mile portion of the entire mapped rearing extent of %.2f miles was modeled using %s. Of the entire mapped rearing extent, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. Floodplain area per unit length was determined for the modeled extent and applied to determine areas for the non-modeled extent. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.', 
                                              watershed_doc_vars$FR_length_modeled_mi,
                                              watershed_doc_vars$FR_rearing_length_mi, 
                                              watershed_doc_vars$model_name, 
                                              watershed_doc_vars$FR_low_gradient_length_mi, 
                                              watershed_doc_vars$FR_high_gradient_length_mi, 
                                              watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'scaled_tr' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for the Tuolumne River based on hydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of the Tuolumne River values based on the ratio of mean flow from December to June between this watershed and the Tuolumne River. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classifiedas low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.',
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$FR_rearing_length_mi, 
                                             watershed_doc_vars$FR_low_gradient_length_mi, 
                                             watershed_doc_vars$FR_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'scaled_cc' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for Cottonwood Creek  based on hydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of Cottonwood Creek values based on the ratio of mean flow from December to June between this watershed and Cottonwood Creek. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was  applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.',
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$FR_rearing_length_mi, 
                                             watershed_doc_vars$FR_low_gradient_length_mi, 
                                             watershed_doc_vars$FR_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor)),
         'sr' = switch(watershed_method,
                       'full_model_nmfs' = sprintf('The entire mapped rearing extent of %.2f miles was modeled using %s. The high quality depth and high quality velocity ("Pref11") "BankArea" result was used as floodplain area. High quality velocities were assumed to be less than or equal to 0.15 meters per second, and high quality depths were assumed to be between 0.2 meters and 1.5 meters.', 
                                                   watershed_doc_vars$SR_rearing_length_mi, 
                                                   watershed_doc_vars$model_name),
                       'full_model' = sprintf("The entire mapped rearing extent of %.2f miles was modeled using %s. Active channel area of %.2f acres estimated through remote sensing analysis was subtracted from total inundated area to get inundated floodplain area.", 
                                              watershed_doc_vars$SR_rearing_length_mi, 
                                              watershed_doc_vars$model_name, 
                                              watershed_doc_vars$SR_channel_area_of_length_modeled_acres),
                       'scaled_dc' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for Deer Creek based onhydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of DeerCreek values based on the ratio of mean flow from December to June between this watershed and Deer Creek. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.', 
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$SR_rearing_length_mi, 
                                             watershed_doc_vars$SR_low_gradient_length_mi, 
                                             watershed_doc_vars$SR_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'part_model' = sprintf('A %.2f mile portion of the entire mapped rearing extent of %.2f miles was modeled using %s. Of the entire mapped rearing extent, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. Floodplain area per unit length was determined for the modeled extent and applied to determine areas for the non-modeled extent. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.', 
                                              watershed_doc_vars$SR_length_modeled_mi,
                                              watershed_doc_vars$SR_rearing_length_mi, 
                                              watershed_doc_vars$model_name, 
                                              watershed_doc_vars$SR_low_gradient_length_mi, 
                                              watershed_doc_vars$SR_high_gradient_length_mi, 
                                              watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'scaled_tr' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for the Tuolumne River based on hydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of the Tuolumne River values based on the ratio of mean flow from December to June between this watershed and the Tuolumne River. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classifiedas low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.',
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$SR_rearing_length_mi, 
                                             watershed_doc_vars$SR_low_gradient_length_mi, 
                                             watershed_doc_vars$SR_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'scaled_cc' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for Cottonwood Creek  based on hydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of Cottonwood Creek values based on the ratio of mean flow from December to June between this watershed and Cottonwood Creek. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was  applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.',
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$SR_rearing_length_mi, 
                                             watershed_doc_vars$SR_low_gradient_length_mi, 
                                             watershed_doc_vars$SR_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor)),
         'st' = switch(watershed_method,
                       'full_model_nmfs' = sprintf('The entire mapped rearing extent of %.2f miles was modeled using %s. The high quality depth and high quality velocity ("Pref11") "BankArea" result was used as floodplain area. High quality velocities were assumed to be less than or equal to 0.15 meters per second, and high quality depths were assumed to be between 0.2 meters and 1.5 meters.', 
                                                   watershed_doc_vars$ST_rearing_length_mi, 
                                                   watershed_doc_vars$model_name),
                       'full_model' = sprintf("The entire mapped rearing extent of %.2f miles was modeled using %s. Active channel area of %.2f acres estimated through remote sensing analysis was subtracted from total inundated area to get inundated floodplain area.", 
                                              watershed_doc_vars$ST_rearing_length_mi, 
                                              watershed_doc_vars$model_name, 
                                              watershed_doc_vars$FR_channel_area_of_length_modeled_acres),
                       'scaled_dc' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for Deer Creek based onhydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of DeerCreek values based on the ratio of mean flow from December to June between this watershed and Deer Creek. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.', 
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$ST_rearing_length_mi, 
                                             watershed_doc_vars$ST_low_gradient_length_mi, 
                                             watershed_doc_vars$ST_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'part_model' = sprintf('A %.2f mile portion of the entire mapped rearing extent of %.2f miles was modeled using %s. Of the entire mapped rearing extent, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. Floodplain area per unit length was determined for the modeled extent and applied to determine areas for the non-modeled extent. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.', 
                                              watershed_doc_vars$ST_length_modeled_mi,
                                              watershed_doc_vars$ST_rearing_length_mi, 
                                              watershed_doc_vars$model_name, 
                                              watershed_doc_vars$ST_low_gradient_length_mi, 
                                              watershed_doc_vars$ST_high_gradient_length_mi, 
                                              watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'scaled_tr' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for the Tuolumne River based on hydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of the Tuolumne River values based on the ratio of mean flow from December to June between this watershed and the Tuolumne River. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classifiedas low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.',
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$ST_rearing_length_mi, 
                                             watershed_doc_vars$ST_low_gradient_length_mi, 
                                             watershed_doc_vars$ST_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor),
                       'scaled_cc' = sprintf('No site-specific hydraulic modeling was available for this watershed. A flow to floodplain area relationship was generated for this watershed by scaling the flow to floodplain area relationship for Cottonwood Creek  based on hydrologic and geomorphic analyses. Flows and corresponding floodplain areas per unit length were calculated for this watershed as %.2f percent of Cottonwood Creek values based on the ratio of mean flow from December to June between this watershed and Cottonwood Creek. Of the entire mapped %.2f mile rearing extent in this watershed, %.2f miles were classified as low gradient and %.2f miles were classified as high gradient based on a geomorphic analysis. A scaling factor of %.1f was  applied to the area per unit length for the high gradient extent. No scaling factor was applied to the low gradient extent.',
                                             watershed_doc_vars$dec_jun_mean_flow_scaling, 
                                             watershed_doc_vars$ST_rearing_length_mi, 
                                             watershed_doc_vars$ST_low_gradient_length_mi, 
                                             watershed_doc_vars$ST_high_gradient_length_mi, 
                                             watershed_doc_vars$high_gradient_floodplain_reduction_factor)))
  
}
